#!/bin/bash

echo "--- begin project specific setup for Camera Gallery Card --"

# TODO
# Add project specific setup directives to this file
# It will be called by "container setup-project" (see devcontainer.json postCreateCommand)
